#!/usr/bin/env node
/* ule前端项目开发启动器 */
require('./console');
require('./init');
var app = require('../ule-server/app');
module.exports = function(){
	require('./ule-modules/hosts')(function(){
		app();
	});
};

