#!/usr/bin/env node

/* ↓↓↓ 输入参数检查 ↓↓↓ */
var args = process.argv.slice(2);
var fs = require('fs');
var path = require('path');
var uledev = require('./uledev');
var arg = '', handle = null;

if(!args.length){
	uledev.killProcess();
	handle = require('./ule-modules/ule-start');
	handle();
}else{
	while(args.length){
		arg = args.shift();
		switch(arg){
			case '-h':
			case 'help':
				var cmdList = require('./ule-conf/uledev-help.json');
				console.info('');
				console.info(cmdList.join('\n'));
				console.info('');
				break;
			case '-v':
			case 'version':
				var packageJson = require('./package.json');
				console.info('\n ', packageJson.name, packageJson.version);
				break;
			case '-s':
			case 'start':
				uledev.killProcess();
				handle = require('./ule-modules/ule-start');
				handle();
				break;
			case 'event':
				// handle = require('./ule-modules/ule-event');
				// handle(args.shift());
				console.info('敬请期待！');
				break;
			case 'base64':
				// handle = require('./ule-modules/ule-base64');
				// handle();
				console.info('敬请期待！');
				break;
			case 'load':
				// handle = require('./ule-modules/ule-load');
				// handle();
				console.info('敬请期待！');
				break;
			default:
				console.info('\r\n  无效命令, 请执行 uledev -h 查询相关命令');
				return;
		}
	}
}