#!/usr/bin/env node

/* ↓↓↓ 输入参数检查 ↓↓↓ */
var args = process.argv.slice(2);
if(!args.length) return console.info('\r\n  简单就是终极的复杂 · 达芬奇');

var fs = require('fs');
var path = require('path');
var extend = require('extend');

var arg = '', handle = null;

while(args.length){
	arg = args.shift();
	switch(arg){
		case '-h':
		case 'help':
			var cmdList = require('./cmd.json');
			console.info('');
			console.info(cmdList.join('\n'));
			console.info('');
			break;
		case '-v':
		case 'version':
			var packageJson = require('./package.json');
			console.info('\n ', packageJson.name, packageJson.version);
			break;
		case '-s':
		case 'start':
			killProcess();
			handle = require('./ule-modules/ule-start');
			handle();
			break;
		case 'event':
			handle = require('./ule-modules/ule-event');
			handle(args.shift());
			break;
		case 'base64':
			handle = require('./ule-modules/ule-base64');
			handle();
			break;
		case 'load':
			handle = require('./ule-modules/ule-load');
			handle();
			break;
		default:
			console.info('\r\n  无效命令, 请执行 uledev -h 查询相关命令');
			return;
	}
}

function killProcess(){
	var exec = require('child_process').exec;
	var oldPid = require('./ule-conf/uledev-pid.json');
	var newPid = process.pid;
	if(oldPid > 0)
		exec('taskkill /F /pid ' + oldPid, function(err, stdout, stderr){});
	fs.writeFileSync(__dirname + '/ule-conf/uledev-pid.json', newPid);
	console.info('[ULE] 启动进程: ', newPid);
}