#!/usr/bin/env node
/* ule前端项目开发启动器 */
require('./ule-modules/console');
require('./ule-modules/init');
module.exports = {
	launch: function(){
		var app = require('./ule-modules/web/app');

		require('./ule-modules/hosts')(function(){
			app.init();
		});
	}
};

